version: 2
jobs:
  meta:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: cd .github/tests && yarn && yarn test

  go:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/graphql-go-server
    steps:
      - checkout
      - run: curl https://s3-eu-west-1.amazonaws.com/curl-linux/prisma-1.34.0.tar.gz | tar xvz && sudo mv prisma /usr/local/bin # TODO (see https://github.com/prisma/prisma/issues/3620)
      - run: cd go/cli-app && prisma generate && dep ensure && go build
      - run: cd go/graphql && prisma generate && dep ensure && go run ./scripts/gqlgen.go && cd server && go build
      - run: cd go/http-mux && prisma generate && dep ensure && go build
      - run: cd go/rest-gin && prisma generate && dep ensure && go build
      - run: cd go/script && prisma generate && dep ensure && go build
      - run: cd go/docker-mongodb && prisma generate && dep ensure && go build
      - run: cd go/docker-mysql && prisma generate && dep ensure && go build
      - run: cd go/docker-postgres && prisma generate && dep ensure && go build

workflows:
  version: 2
  build:
    jobs:
      - go
